spring.config.import=application_prod.properties
spring.profiles.active=default
spring.application.name=${SPRING_APPLICATION_NAME:bank-management-system}
logging.pattern.console=${LOGGING_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
#spring.security.user.name= ${SECURITY_USERNAME:karim}
#spring.security.user.password=${SECURITY_PASSWORD:Karim_Alaa}
spring.datasource.url=jdbc:postgresql://${HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:bank_management_system}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:0000}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:http://localhost:8180/realms/Bank_Management_app/protocol/openid-connect/certs}

#spring.security.oauth2.resourceserver.opaque.introspection-uri= ${INTROSPECT_URI:http://localhost:8180/realms/Bank_Management_app/protocol/openid-connect/token/introspect}
#spring.security.oauth2.resourceserver.opaque.introspection-client-id=${INTROSPECT_ID:bankmanagementintrospect}
#spring.security.oauth2.resourceserver.opaque.introspection-client-secret=${INTROSPECT_SECRET:sUoJY5WTsCDTaHKKVCDTj5VuqJglDEcXjRGPiLcdWw69E5lWsaAiqhZKCfNp8vISp9ACkVp8EjeEjOVB5tkD50}