spring.application.name=${SPRING_APPLICATION_NAME:bank-management-system}
logging.pattern.console=${LOGGING_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
#spring.security.user.name= ${SECURITY_USERNAME:karim}
#spring.security.user.password=${SECURITY_PASSWORD:Karim_Alaa}
spring.datasource.url=jdbc:postgresql://${HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:bank_management_system}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:0000}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}